

-- CREATION DE LA BASE DE DONNEES 

CREATE DATABASE MASDDB;-- UTILISATION DE LA BASE DE DONNEES USE MASDDB;-- LES TYPES DE DONNÉES SQL SERVER ET DE LEURS TYPES LES PLUS COURAMMENT UTILISÉS --

-- TYPES NUMÉRIQUES EXACTS :
/*
- BIGINT : ENTIER DE 8 OCTETS, DE -9,223,372,036,854,775,808 À 9,223,372,036,854,775,807
- INT : ENTIER DE 4 OCTETS, DE -2,147,483,648 À 2,147,483,647
- SMALLINT : ENTIER DE 2 OCTETS, DE -32,768 À 32,767
- TINYINT : ENTIER DE 1 OCTET, DE 0 À 255
- BIT : VALEUR BOOLÉENNE, 0 OU 1
- DECIMAL/NUMERIC : NOMBRE DÉCIMAL PRÉCIS
- MONEY : VALEUR MONÉTAIRE PRÉCISE
- SMALLMONEY : VALEUR MONÉTAIRE MOINS PRÉCISE

TYPES NUMÉRIQUES APPROXIMATIFS :
- FLOAT : NOMBRE EN VIRGULE FLOTTANTE, DE ±1.79E + 308 À ±1.79E + 308
- REAL : NOMBRE EN VIRGULE FLOTTANTE SIMPLE PRÉCISION, DE -3.40E + 38 À 3.40E + 38

TYPES DATETIME :
- DATETIME : DATE ET HEURE JUSQU'À LA PRÉCISION DE MILLISECONDES
- SMALLDATETIME : DATE ET HEURE AVEC UNE PRÉCISION DE MINUTES

CHAÎNES DE CARACTÈRES :
- CHAR : CHAÎNE DE LONGUEUR FIXE EN UNICODE JUSQU'À 8000 CARACTÈRES
- VARCHAR : CHAÎNE DE LONGUEUR VARIABLE EN UNICODE JUSQU'À 2 GO
- TEXT : CHAÎNE DE LONGUEUR MAXIMALE NON-UNICODE JUSQU'À 2 GO

CHAÎNES DE CARACTÈRES UNICODE :
- NCHAR : CHAÎNE DE LONGUEUR FIXE EN UNICODE JUSQU'À 4000 CARACTÈRES
- NVARCHAR : CHAÎNE DE LONGUEUR VARIABLE EN UNICODE JUSQU'À 4000 CARACTÈRES
- NVARCHAR(MAX) : CHAÎNE DE LONGUEUR VARIABLE EN UNICODE JUSQU'À 2^30 CARACTÈRES
- NTEXT : CHAÎNE DE LONGUEUR MAXIMALE EN UNICODE JUSQU'À 1,073,741,823 CARACTÈRES

BINARY CORDES :
- BINARY : DONNÉES BINAIRES DE LONGUEUR FIXE JUSQU'À 8000 OCTETS
- VARBINARY : DONNÉES BINAIRES DE LONGUEUR VARIABLE JUSQU'À 8000 OCTETS
- VARBINARY(MAX) : DONNÉES BINAIRES DE LONGUEUR VARIABLE JUSQU'À 2^31 OCTETS
- IMAGE : DONNÉES BINAIRES DE LONGUEUR MAXIMALE JUSQU'À 2,147,483,647 OCTETS
*/-- EXEMPLE 1
-- CREATION DE LA TABLE ELEVE 
-- LA NUMÉROTATION AUTOMATIQUE COMMENCE À 1 ET ELLE EST À PAS DE 1.CREATE TABLE ELEVE
(
	NUM INT IDENTITY,
	NOM VARCHAR(30),
	PRENOM VARCHAR(30),
	CONSTRAINT PKELEVE PRIMARY KEY(NUM)
);

-- INSERTION DANS LA TABLE ELEVE 

INSERT INTO ELEVE (NOM,PRENOM) VALUES('PATOCHE','ALAIN');
INSERT INTO ELEVE (NOM,PRENOM) VALUES('SIMBA','CHAT');-- VOIRE LE CONTENU DE LA TABLE SELECT * FROM ELEVE-- EXEMPLE 2
-- CREATION DE LA TABLE CLIENTSINFO
-- LA NUMÉROTATION AUTOMATIQUE COMMENCE À 10 ET ELLE EST À PAS DE 2.

CREATE TABLE CLIENTSINFO
(
	NUMCLIENT SMALLINT IDENTITY(10,2),
	NOMCLIENT VARCHAR(30),
	CONSTRAINT PKCL PRIMARY KEY (NUMCLIENT)
);


-- INSERTION DANS LA TABLE CLIENTINFO 

INSERT INTO CLIENTSINFO (NOMCLIENT) VALUES ('ABDELFATTAH BOUHLALI');INSERT INTO CLIENTSINFO (NOMCLIENT) VALUES ('MOUAD EL AMMARI');INSERT INTO CLIENTSINFO (NOMCLIENT) VALUES ('NOUR EDDINE GAJJA');-- SELECTIONNER LE CONTENU DE LA TABLE SELECT * FROM CLIENTSINFO;-- SION ON VEUT FAIRE UNE INSERTION MANUELLE DANS LA COLONNE NUM (IDENTITY) IL FAUT METTRE 

-- INDENTITY_INSERT A ONSET IDENTITY_INSERT ELEVE ON;


-- INSERTION DANS LA TABLE ELEVE 

INSERT INTO ELEVE (NUM,NOM, PRENOM) VALUES (20,'SIMPSON','FRED');-- VOIRE LE CONTENU DE LA TABLE SELECT * FROM ELEVE;-- MAINTENANT SI VOUS VOULEZ AJOUTER UN ELEMENT COMME SUIT INSERT INTO ELEVE (NOM, PRENOM) VALUES ('SIMPSON','FRED');-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-- CETTE COMMANDE "SET IDENTITY_INSERT ELEVE ON;" -- NOUS OBLIGE À INSÉRER LE "NUM" CHAQUE FOIS QUE-- NOUS VOULONS AJOUTER UN ÉLÉMENT DANS LA TABLE.-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-- CORRECTIONINSERT INTO ELEVE (NUM , NOM , PRENOM) VALUES (24, 'MOURAD','MOMED');-- VOIRE LE CONTENU DE LA TABLE SELECT * FROM ELEVE;-- INSERTION DE MULTIPLES LIGNES INSERT INTO ELEVE (NUM , NOM , PRENOM) VALUES (25, 'AHMED','MOHAMED') , (26, 'CHAKIR','SALMI');-- VOIRE LE CONTENU DE LA TABLE SELECT * FROM ELEVE;-- POUR ANNULER L'INSERTION MANUEL DE "NUME"SET IDENTITY_INSERT ELEVE OFF ;INSERT INTO ELEVE VALUES ('AHMED','MOHAMED') , ('CHAKIR','SALMI');-- METTRE LA REQUETTE A L'INTERIEUR D'UNE TRANSACTION BEGIN TRANSACTIONINSERT INTO ELEVE VALUES ('MOHMOUD','KASOUL');INSERT INTO ELEVE VALUES ('MOHAMMED','KASOUL');INSERT INTO ELEVE VALUES ('KAMAL','KASOUL');COMMIT;